remote_theme: pmarsceill/just-the-docs
title: RV32IM Pipeline Implementation
logo: "/images/uop.png"
description: A pipeline implementation that supports RV32IM ISA.

# Aux links for the upper right navigation
aux_links:
  "Project Repository on GitHub":
    - "//github.com/cepdnaclk/e16-co502-RV32IM-pipeline-implementation-group1"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

color_scheme: dark
